//! Generated API assembly bootstrap for sdkwork-web-framework.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use sdkwork_web_framework_admin_repository_sqlx::AdminStorePool;

pub struct ApiAssembly {
    pub router: Router,
}

pub fn assemble_api_router(pool: AdminStorePool) -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_web_framework_backend_api::gateway_mount(
        pool,
    ));
    ApiAssembly { router }
}
