use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde_json::{Map, Value};

const HTTP_METHODS: &[(&str, &str)] = &[
    ("delete", "HttpMethod::Delete"),
    ("get", "HttpMethod::Get"),
    ("patch", "HttpMethod::Patch"),
    ("post", "HttpMethod::Post"),
    ("put", "HttpMethod::Put"),
];

pub fn generate_http_route_manifest(
    openapi_path: impl AsRef<Path>,
    output_path: impl AsRef<Path>,
    constant_name: &str,
) -> Result<(), String> {
    validate_constant_name(constant_name)?;
    let openapi_path = openapi_path.as_ref();
    let source = fs::read_to_string(openapi_path)
        .map_err(|error| format!("read OpenAPI {} failed: {error}", openapi_path.display()))?;
    let document: Value = serde_json::from_str(&source)
        .map_err(|error| format!("parse OpenAPI {} failed: {error}", openapi_path.display()))?;
    let generated = render_http_route_manifest(&document, constant_name)?;
    fs::write(output_path.as_ref(), generated).map_err(|error| {
        format!(
            "write generated route manifest {} failed: {error}",
            output_path.as_ref().display()
        )
    })
}

pub fn render_http_route_manifest(document: &Value, constant_name: &str) -> Result<String, String> {
    validate_constant_name(constant_name)?;
    let paths = document
        .get("paths")
        .and_then(Value::as_object)
        .ok_or_else(|| "OpenAPI document must contain a paths object".to_owned())?;
    let root_security = document.get("security");
    let mut output = String::from(
        "// @generated by sdkwork-web-build from the route crate's OpenAPI authority; do not edit.\n\
use sdkwork_web_core::{HttpMethod, HttpRoute, RouteAuth};\n\n",
    );
    writeln!(output, "pub const {constant_name}: &[HttpRoute] = &[")
        .map_err(|error| error.to_string())?;

    for (path, path_item) in paths {
        let path_item = path_item
            .as_object()
            .ok_or_else(|| format!("OpenAPI path {path} must be an object"))?;
        for (method, rust_method) in HTTP_METHODS {
            let Some(operation) = path_item.get(*method) else {
                continue;
            };
            let operation = operation.as_object().ok_or_else(|| {
                format!(
                    "OpenAPI operation {} {path} must be an object",
                    method.to_uppercase()
                )
            })?;
            let operation_id = required_string(operation, "operationId", method, path)?;
            let tag = operation
                .get("tags")
                .and_then(Value::as_array)
                .and_then(|tags| tags.first())
                .and_then(Value::as_str)
                .unwrap_or("default");
            let auth = route_auth(operation, root_security)?;
            write!(
                output,
                "    HttpRoute::new({rust_method}, {:?}, {:?}, {:?}, {auth})",
                path, tag, operation_id
            )
            .map_err(|error| error.to_string())?;
            if operation
                .get("x-sdkwork-idempotent")
                .and_then(Value::as_bool)
                .unwrap_or(false)
            {
                output.push_str(".with_idempotent(true)");
            }
            if let Some(permission) = operation
                .get("x-sdkwork-permission")
                .and_then(Value::as_str)
                .filter(|permission| !permission.trim().is_empty())
            {
                write!(output, ".with_required_permission({permission:?})")
                    .map_err(|error| error.to_string())?;
            }
            if operation
                .get("x-sdkwork-forbid-credential-headers")
                .and_then(Value::as_bool)
                .unwrap_or(false)
            {
                output.push_str(".with_forbid_credential_headers(true)");
            }
            if let Some(retention) = operation
                .get("x-sdkwork-log-retention")
                .and_then(Value::as_str)
                .filter(|retention| !retention.trim().is_empty())
            {
                write!(output, ".with_log_retention({retention:?})")
                    .map_err(|error| error.to_string())?;
            }
            output.push_str(",\n");
        }
    }
    output.push_str("];\n");
    Ok(output)
}

fn validate_constant_name(constant_name: &str) -> Result<(), String> {
    if constant_name.is_empty()
        || !constant_name
            .bytes()
            .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
    {
        return Err("route manifest constant name must be SCREAMING_SNAKE_CASE".to_owned());
    }
    Ok(())
}

fn required_string<'a>(
    operation: &'a Map<String, Value>,
    field: &str,
    method: &str,
    path: &str,
) -> Result<&'a str, String> {
    operation
        .get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .ok_or_else(|| {
            format!(
                "OpenAPI operation {} {path} must declare {field}",
                method.to_uppercase()
            )
        })
}

fn route_auth(
    operation: &Map<String, Value>,
    root_security: Option<&Value>,
) -> Result<&'static str, String> {
    if let Some(mode) = operation.get("x-sdkwork-auth-mode").and_then(Value::as_str) {
        return auth_mode(mode);
    }
    let security = operation.get("security").or(root_security);
    let Some(requirements) = security.and_then(Value::as_array) else {
        return Ok("RouteAuth::Public");
    };
    if requirements.is_empty() {
        return Ok("RouteAuth::Public");
    }
    let scheme_names = requirements
        .iter()
        .filter_map(Value::as_object)
        .flat_map(|requirement| requirement.keys())
        .map(|name| name.to_ascii_lowercase())
        .collect::<Vec<_>>();
    let has_auth = scheme_names.iter().any(|name| name.contains("auth"));
    let has_access = scheme_names.iter().any(|name| name.contains("access"));
    if has_auth && has_access {
        Ok("RouteAuth::DualToken")
    } else if scheme_names
        .iter()
        .any(|name| name.contains("apikey") || name.contains("api_key"))
    {
        Ok("RouteAuth::ApiKey")
    } else if scheme_names
        .iter()
        .any(|name| name.contains("oauth") || name.contains("bearer"))
    {
        Ok("RouteAuth::OAuth")
    } else {
        Err(format!(
            "unsupported OpenAPI security requirement: {}",
            scheme_names.join(", ")
        ))
    }
}

fn auth_mode(mode: &str) -> Result<&'static str, String> {
    match mode.trim().to_ascii_lowercase().as_str() {
        "anonymous" | "public" => Ok("RouteAuth::Public"),
        "bootstrap-body" => Ok("RouteAuth::BootstrapBody"),
        "credential-entry-bootstrap" => Ok("RouteAuth::CredentialEntryBootstrap"),
        "dual-token" => Ok("RouteAuth::DualToken"),
        "api-key" => Ok("RouteAuth::ApiKey"),
        "ingress-token" => Ok("RouteAuth::IngressToken"),
        "oauth" => Ok("RouteAuth::OAuth"),
        "open-api-flexible" => Ok("RouteAuth::OpenApiFlexible"),
        "open-api-bearer-flexible" => Ok("RouteAuth::OpenApiBearerFlexible"),
        "api-key-or-dual-token" => Ok("RouteAuth::ApiKeyOrDualToken"),
        "refresh-token" => Ok("RouteAuth::RefreshToken"),
        "agent-token" => Ok("RouteAuth::AgentToken"),
        other => Err(format!("unsupported x-sdkwork-auth-mode {other:?}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn preserves_operation_inventory_and_infers_dual_token_security() {
        let source = json!({
            "paths": {
                "/app/v3/api/widgets/{widgetId}": {
                    "get": {
                        "operationId": "widgets.retrieve",
                        "tags": ["widgets"],
                        "security": [{"AuthToken": [], "AccessToken": []}],
                        "x-sdkwork-permission": "widgets.read"
                    }
                }
            }
        });
        let generated = render_http_route_manifest(&source, "WIDGET_ROUTES").unwrap();
        assert!(generated.contains("RouteAuth::DualToken"));
        assert!(generated.contains("widgets.retrieve"));
        assert!(generated.contains("with_required_permission(\"widgets.read\")"));
    }

    #[test]
    fn rejects_unknown_security_instead_of_weakening_authentication() {
        let source = json!({
            "paths": {"/v1/widgets": {"get": {
                "operationId": "widgets.list",
                "security": [{"Unknown": []}]
            }}}
        });
        assert!(render_http_route_manifest(&source, "WIDGET_ROUTES")
            .unwrap_err()
            .contains("unsupported OpenAPI security"));
    }

    #[test]
    fn maps_canonical_anonymous_auth_mode_to_public_route_auth() {
        let source = json!({
            "paths": {"/app/v3/api/widgets": {"get": {
                "operationId": "widgets.list",
                "x-sdkwork-auth-mode": "anonymous",
                "security": []
            }}}
        });

        let generated = render_http_route_manifest(&source, "WIDGET_ROUTES").unwrap();

        assert!(generated.contains("RouteAuth::Public"));
    }

    #[test]
    fn round_trips_log_retention_annotation() {
        let source = json!({
            "paths": {"/backend/v3/api/billing/records": {"get": {
                "operationId": "billing.records.list",
                "tags": ["billing"],
                "security": [{"AuthToken": [], "AccessToken": []}],
                "x-sdkwork-log-retention": "permanent"
            }}}
        });

        let generated = render_http_route_manifest(&source, "WIDGET_ROUTES").unwrap();

        assert!(generated.contains("with_log_retention(\"permanent\")"));
    }
}
