//! Generated gateway bootstrap for sdkwork-web-framework.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sqlx::SqlitePool;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router(pool: SqlitePool) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_web_framework_backend_api::gateway_mount(
        pool,
    ));
    ApplicationAssembly { router }
}
