//! Route manifest for framework control-plane backend-api (`WEB_BACKEND_SPEC.md`).

use crate::paths;
use crate::tenant_scope::{PERM_CONTROL_PLANE, PERM_PLATFORM_READ, PERM_TENANT_ADMIN};
use sdkwork_web_contract::{HttpMethod, HttpRoute};

pub const ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::cors::PATH,
        "WebFramework",
        "webFramework.corsPolicies.list",
    )
    .with_required_permission(PERM_TENANT_ADMIN)
    .with_alternate_permissions(&[PERM_PLATFORM_READ]),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::cors::PATH,
        "WebFramework",
        "webFramework.corsPolicies.upsert",
    )
    .with_required_permission(PERM_TENANT_ADMIN),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::rate_limit::PATH,
        "WebFramework",
        "webFramework.rateLimitPolicies.list",
    )
    .with_required_permission(PERM_TENANT_ADMIN)
    .with_alternate_permissions(&[PERM_PLATFORM_READ]),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::rate_limit::PATH,
        "WebFramework",
        "webFramework.rateLimitPolicies.upsert",
    )
    .with_required_permission(PERM_TENANT_ADMIN),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::tenant_runtime::PATH,
        "WebFramework",
        "webFramework.tenantRuntimeProfiles.list",
    )
    .with_required_permission(PERM_TENANT_ADMIN)
    .with_alternate_permissions(&[PERM_PLATFORM_READ]),
    HttpRoute::dual_token(
        HttpMethod::Put,
        paths::tenant_runtime::PATH,
        "WebFramework",
        "webFramework.tenantRuntimeProfiles.upsert",
    )
    .with_required_permission(PERM_TENANT_ADMIN),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::security_events::PATH,
        "WebFramework",
        "webFramework.securityEvents.list",
    )
    .with_required_permission(PERM_CONTROL_PLANE),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::audit_events::PATH,
        "WebFramework",
        "webFramework.auditEvents.list",
    )
    .with_required_permission(PERM_TENANT_ADMIN)
    .with_alternate_permissions(&[PERM_PLATFORM_READ]),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::control_nodes::COLLECTION,
        "WebFramework",
        "webFramework.controlNodes.list",
    )
    .with_required_permission(PERM_CONTROL_PLANE),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::control_nodes::COLLECTION,
        "WebFramework",
        "webFramework.controlNodes.register",
    )
    .with_required_permission(PERM_CONTROL_PLANE),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::control_nodes::HEARTBEAT,
        "WebFramework",
        "webFramework.controlNodes.heartbeat",
    )
    .with_required_permission(PERM_CONTROL_PLANE),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::control_nodes::BY_ID,
        "WebFramework",
        "webFramework.controlNodes.delete",
    )
    .with_required_permission(PERM_CONTROL_PLANE),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::runtime_defaults::PATH,
        "WebFramework",
        "webFramework.runtimeDefaults.snapshot",
    )
    .with_required_permission(PERM_TENANT_ADMIN),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::optional_features::PATH,
        "WebFramework",
        "webFramework.optionalFeatures.snapshot",
    )
    .with_required_permission(PERM_TENANT_ADMIN),
];
