-- SDKWork webstore consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_framework_baseline.sql
-- Consolidated legacy baseline imported by bootstrap-database-module.mjs
-- Review and replace with contract-first migrations.
-- Engine: PostgreSQL. Consolidates migrations 001-014 into final-state DDL.

-- source: crates/sdkwork-web-store-sqlx/migrations/001_framework_stores.sql + 011 + 013(partial)
CREATE TABLE IF NOT EXISTS framework_idempotency_record (
    idempotency_key TEXT PRIMARY KEY NOT NULL,
    fingerprint TEXT NOT NULL,
    response_status INTEGER,
    response_body BYTEA,
    content_type TEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    tenant_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_framework_idempotency_expires
    ON framework_idempotency_record (expires_at);

CREATE INDEX IF NOT EXISTS idx_framework_idempotency_tenant
    ON framework_idempotency_record (tenant_id);

CREATE INDEX IF NOT EXISTS idx_framework_idempotency_tenant_expires
    ON framework_idempotency_record (tenant_id, expires_at);

CREATE TABLE IF NOT EXISTS framework_security_event (
    id BIGSERIAL PRIMARY KEY,
    kind TEXT NOT NULL,
    request_id TEXT,
    path TEXT NOT NULL,
    method TEXT NOT NULL,
    api_surface TEXT NOT NULL,
    origin TEXT,
    detail TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    tenant_id TEXT,
    expires_at BIGINT
);

CREATE INDEX IF NOT EXISTS idx_framework_security_event_created
    ON framework_security_event (created_at);

CREATE INDEX IF NOT EXISTS idx_framework_security_event_tenant
    ON framework_security_event (tenant_id);

CREATE INDEX IF NOT EXISTS idx_framework_security_event_tenant_created
    ON framework_security_event (tenant_id, created_at);

CREATE INDEX IF NOT EXISTS idx_framework_security_event_expires
    ON framework_security_event (expires_at);

-- source: crates/sdkwork-web-store-sqlx/migrations/002_framework_rate_limit_bucket.sql + 012
CREATE TABLE IF NOT EXISTS framework_rate_limit_bucket (
    bucket_key TEXT PRIMARY KEY NOT NULL,
    request_count INTEGER NOT NULL,
    window_start BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    tenant_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_framework_rate_limit_expires
    ON framework_rate_limit_bucket (expires_at);

CREATE INDEX IF NOT EXISTS idx_framework_rate_limit_tenant
    ON framework_rate_limit_bucket (tenant_id);

CREATE INDEX IF NOT EXISTS idx_framework_rate_limit_tenant_expires
    ON framework_rate_limit_bucket (tenant_id, expires_at);

-- source: crates/sdkwork-web-store-sqlx/migrations/003_framework_audit_event.sql + 009 + 013
CREATE TABLE IF NOT EXISTS framework_audit_event (
    id BIGSERIAL PRIMARY KEY,
    request_id TEXT NOT NULL,
    tenant_id TEXT,
    user_id TEXT,
    api_surface TEXT NOT NULL,
    path TEXT NOT NULL,
    method TEXT NOT NULL,
    operation_id TEXT,
    created_at BIGINT NOT NULL,
    status_code INTEGER,
    duration_ms INTEGER,
    expires_at BIGINT
);

CREATE INDEX IF NOT EXISTS idx_framework_audit_event_created
    ON framework_audit_event (created_at);

CREATE INDEX IF NOT EXISTS idx_framework_audit_event_request
    ON framework_audit_event (request_id);

CREATE INDEX IF NOT EXISTS idx_framework_audit_event_tenant
    ON framework_audit_event (tenant_id);

CREATE INDEX IF NOT EXISTS idx_framework_audit_expires
    ON framework_audit_event (expires_at);

-- source: crates/sdkwork-web-store-sqlx/migrations/004_framework_cors_policy.sql + 014
CREATE TABLE IF NOT EXISTS framework_cors_policy (
    tenant_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    allow_all_origins INTEGER NOT NULL DEFAULT 0,
    allowed_origins TEXT NOT NULL,
    allow_credentials INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (tenant_id, environment)
);

CREATE INDEX IF NOT EXISTS idx_framework_cors_policy_tenant
    ON framework_cors_policy (tenant_id);

-- source: crates/sdkwork-web-store-sqlx/migrations/005_framework_rate_limit_policy.sql + 014
CREATE TABLE IF NOT EXISTS framework_rate_limit_policy (
    tenant_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    tier_key TEXT NOT NULL DEFAULT 'default',
    max_requests INTEGER NOT NULL,
    window_secs INTEGER NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (tenant_id, environment, tier_key)
);

CREATE INDEX IF NOT EXISTS idx_framework_rate_limit_policy_tenant
    ON framework_rate_limit_policy (tenant_id);

-- source: crates/sdkwork-web-store-sqlx/migrations/006_framework_tenant_runtime_profile.sql + 008 + 014
CREATE TABLE IF NOT EXISTS framework_tenant_runtime_profile (
    tenant_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    rate_limit_enabled INTEGER,
    max_content_length INTEGER,
    max_concurrent_requests INTEGER,
    version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (tenant_id, environment)
);

CREATE INDEX IF NOT EXISTS idx_framework_tenant_runtime_profile_tenant
    ON framework_tenant_runtime_profile (tenant_id);

-- source: crates/sdkwork-web-store-sqlx/migrations/007_framework_control_node.sql
CREATE TABLE IF NOT EXISTS framework_control_node (
    node_id TEXT PRIMARY KEY NOT NULL,
    region TEXT NOT NULL DEFAULT 'default',
    base_url TEXT NOT NULL,
    environment TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'registered',
    last_heartbeat_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_framework_control_node_environment
    ON framework_control_node (environment);

CREATE INDEX IF NOT EXISTS idx_framework_control_node_region
    ON framework_control_node (region);
